const ShopActionsType = {
    //UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS' //we don`t need it anymore because we sent our data to firebase
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE' 
}
export default ShopActionsType;